#!/usr/bin/env Rscript
# =============================================================================
# Potomac Pulse Phase 3, Task 4: Validate Tributary Timing Calculations (R)
#
# Cross-correlates Monocacy and Goose Creek tributary discharge with Little Falls
# discharge to determine optimal time lags, and quantifies the RMSE impact of
# applying those lags vs the current (no-lag) approach.
#
# Requires:
#   - analysis/hourly_backtest_data.csv  (117k hourly obs)
#   - analysis/tributary_hourly_data.csv (generated by Python companion script)
#
# Output:
#   - analysis/validate_tributary_timing_R.csv
#
# Uses base R only (no extra packages).
# =============================================================================

set.seed(42)

# -- Define helper operator before first use ----------------------------------
`%s%` <- function(a, b) paste0(a, b)

# -- File paths ---------------------------------------------------------------
base_dir    <- "/Users/sebjilke/Desktop/PotomacPulse/analysis"
backtest_f  <- base_dir %s% "/hourly_backtest_data.csv"
tributary_f <- base_dir %s% "/tributary_hourly_data.csv"
output_f    <- base_dir %s% "/validate_tributary_timing_R.csv"

# -- Check that input files exist ---------------------------------------------
if (!file.exists(backtest_f)) {
  stop("Backtest data not found: " %s% backtest_f %s%
       "\nRun the backtest data generation script first.")
}
if (!file.exists(tributary_f)) {
  stop("Tributary data not found: " %s% tributary_f %s%
       "\nRun the Python tributary data script (validate_tributary_timing.py) first " %s%
       "to fetch Monocacy and Goose Creek hourly data from USGS.")
}

cat("Loading backtest data...\n")
bt <- read.csv(backtest_f, stringsAsFactors = FALSE)
bt$timestamp <- as.POSIXct(bt$timestamp, format = "%Y-%m-%d %H:%M", tz = "UTC")
cat("  Backtest rows: ", nrow(bt), "\n")

cat("Loading tributary data...\n")
trib <- read.csv(tributary_f, stringsAsFactors = FALSE)
trib$timestamp <- as.POSIXct(trib$timestamp, format = "%Y-%m-%d %H:%M:%S", tz = "UTC")
# Handle column names: Python may use monocacy_q/goose_q or monocacy_discharge/goose_discharge
if ("monocacy_q" %in% names(trib)) names(trib)[names(trib) == "monocacy_q"] <- "monocacy_discharge"
if ("goose_q" %in% names(trib)) names(trib)[names(trib) == "goose_q"] <- "goose_discharge"
cat("  Tributary rows: ", nrow(trib), "\n")

# -- Merge on timestamp -------------------------------------------------------
cat("Merging on timestamp...\n")
df <- merge(bt, trib, by = "timestamp", all = FALSE)
df <- df[order(df$timestamp), ]
cat("  Merged rows: ", nrow(df), "\n")

if (nrow(df) == 0) {
  stop("No matching timestamps between backtest and tributary data. " %s%
       "Check timestamp formats.")
}

# -- Build a lookup environment for fast timestamp-based matching -------------
# We store tributary values keyed by integer seconds-since-epoch for O(1) lookup.
cat("Building timestamp lookup tables...\n")

ts_seconds <- as.numeric(df$timestamp)  # seconds since epoch

# Lookup environments: key = character(seconds), value = discharge
mono_env  <- new.env(hash = TRUE, parent = emptyenv(), size = nrow(df))
goose_env <- new.env(hash = TRUE, parent = emptyenv(), size = nrow(df))
lf_env    <- new.env(hash = TRUE, parent = emptyenv(), size = nrow(df))

for (i in seq_len(nrow(df))) {
  key <- as.character(ts_seconds[i])
  if (!is.na(df$monocacy_discharge[i])) {
    assign(key, df$monocacy_discharge[i], envir = mono_env)
  }
  if (!is.na(df$goose_discharge[i])) {
    assign(key, df$goose_discharge[i], envir = goose_env)
  }
  if (!is.na(df$lf_discharge[i])) {
    assign(key, df$lf_discharge[i], envir = lf_env)
  }
}

# Helper: look up a value by timestamp + lag (in hours) from an environment
lookup_lagged <- function(ts_sec, lag_h, env) {
  # ts_sec: numeric vector of seconds-since-epoch

  # lag_h:  scalar lag in hours (tributary reading is lag_h hours BEFORE the LF reading,
  #         so we subtract lag_h from the LF timestamp to find the tributary timestamp)
  shifted <- as.character(ts_sec - lag_h * 3600)
  result  <- rep(NA_real_, length(shifted))
  for (i in seq_along(shifted)) {
    val <- tryCatch(get(shifted[i], envir = env, inherits = FALSE),
                    error = function(e) NA_real_)
    result[i] <- val
  }
  result
}

# -- Flow regime classification -----------------------------------------------
classify_regime <- function(lf) {
  regime <- rep(NA_character_, length(lf))
  regime[!is.na(lf) & lf < 5000]                       <- "<5k"
  regime[!is.na(lf) & lf >= 5000  & lf < 15000]        <- "5-15k"
  regime[!is.na(lf) & lf >= 15000 & lf < 50000]        <- "15-50k"
  regime[!is.na(lf) & lf >= 50000]                      <- ">50k"
  regime
}

df$flow_regime <- classify_regime(df$lf_discharge)

# -- Cross-correlation on first-differences -----------------------------------
# We compute Pearson correlation between delta(tributary_lagged) and delta(LF)
# for each lag and flow regime.

cat("Running cross-correlation analysis...\n")

# Lag grids (hours)
mono_lags  <- seq(0, 12, by = 0.5)   # 0 to 12h in 0.5h steps
goose_lags <- seq(0, 6,  by = 0.5)   # 0 to 6h in 0.5h steps

regimes <- c("<5k", "5-15k", "15-50k", ">50k")

# Container for cross-correlation results
xcorr_results <- data.frame(
  tributary       = character(),
  flow_regime     = character(),
  lag_h           = numeric(),
  correlation     = numeric(),
  n_pairs         = integer(),
  stringsAsFactors = FALSE
)

compute_xcorr <- function(trib_name, trib_env, lag_grid) {
  cat("  Processing " %s% trib_name %s% "...\n")
  for (regime in regimes) {
    idx <- which(df$flow_regime == regime)
    if (length(idx) < 20) {
      cat("    " %s% regime %s% ": too few obs (" %s%
          as.character(length(idx)) %s% "), skipping\n")
      next
    }
    regime_ts  <- ts_seconds[idx]
    regime_lf  <- df$lf_discharge[idx]

    for (lag in lag_grid) {
      # Look up tributary values at (timestamp - lag)
      trib_vals <- lookup_lagged(regime_ts, lag, trib_env)

      # First differences: we need consecutive timestamps (1h apart) in the regime
      # Compute delta = value[i] - value[i-1] only when timestamps are 1h apart
      dt <- diff(regime_ts)
      valid_consecutive <- which(dt == 3600)

      if (length(valid_consecutive) < 10) next

      delta_lf   <- regime_lf[valid_consecutive + 1] - regime_lf[valid_consecutive]
      delta_trib <- trib_vals[valid_consecutive + 1]  - trib_vals[valid_consecutive]

      # Remove NAs
      ok <- !is.na(delta_lf) & !is.na(delta_trib)
      n  <- sum(ok)
      if (n < 10) next

      corr <- cor(delta_trib[ok], delta_lf[ok])

      xcorr_results <<- rbind(xcorr_results, data.frame(
        tributary   = trib_name,
        flow_regime = regime,
        lag_h       = lag,
        correlation = corr,
        n_pairs     = n,
        stringsAsFactors = FALSE
      ))
    }
  }
}

compute_xcorr("monocacy", mono_env, mono_lags)
compute_xcorr("goose",    goose_env, goose_lags)

# -- Find optimal lag per tributary per regime --------------------------------
cat("Identifying optimal lags...\n")

optimal_lags <- data.frame(
  tributary        = character(),
  flow_regime      = character(),
  optimal_lag_h    = numeric(),
  peak_correlation = numeric(),
  n_obs            = integer(),
  stringsAsFactors = FALSE
)

for (trib_name in c("monocacy", "goose")) {
  for (regime in regimes) {
    sub <- xcorr_results[xcorr_results$tributary == trib_name &
                         xcorr_results$flow_regime == regime, ]
    if (nrow(sub) == 0) {
      optimal_lags <- rbind(optimal_lags, data.frame(
        tributary        = trib_name,
        flow_regime      = regime,
        optimal_lag_h    = NA_real_,
        peak_correlation = NA_real_,
        n_obs            = 0L,
        stringsAsFactors = FALSE
      ))
      next
    }
    best <- sub[which.max(sub$correlation), ]
    optimal_lags <- rbind(optimal_lags, data.frame(
      tributary        = best$tributary,
      flow_regime      = best$flow_regime,
      optimal_lag_h    = best$lag_h,
      peak_correlation = best$correlation,
      n_obs            = best$n_pairs,
      stringsAsFactors = FALSE
    ))
  }
}

cat("\nOptimal lags:\n")
print(optimal_lags)

# -- RMSE impact analysis ----------------------------------------------------
cat("\nComputing RMSE impact...\n")

# Reconstruct the v29.0 blended estimate
# EF power law: 126 * ef_stage^2.46 (default), 160 * ef_stage^2.36 (cold <= 10C)
# EF weight: 0% when lf_discharge < 3000, 35% when >= 3000
# blended_por = (1 - ef_weight) * por_lagged + ef_weight * ef_cfs

df$ef_cfs <- ifelse(!is.na(df$water_temp_c) & df$water_temp_c <= 10,
                    160 * df$ef_stage^2.36,
                    126 * df$ef_stage^2.46)

df$ef_weight <- ifelse(!is.na(df$lf_discharge) & df$lf_discharge >= 3000, 0.35, 0.0)

df$blended_por <- (1 - df$ef_weight) * df$por_lagged + df$ef_weight * df$ef_cfs

# Current approach: tributaries at lag 0 (current readings)
df$mono_current  <- lookup_lagged(ts_seconds, 0, mono_env)
df$goose_current <- lookup_lagged(ts_seconds, 0, goose_env)

df$gf_current <- df$blended_por +
  df$mono_current  * 0.071 +
  df$goose_current * 0.030

# For each regime, compute shifted estimate using optimal lags
# We need per-regime optimal lags for each tributary
get_optimal_lag <- function(trib_name, regime) {
  row <- optimal_lags[optimal_lags$tributary == trib_name &
                      optimal_lags$flow_regime == regime, ]
  if (nrow(row) == 0 || is.na(row$optimal_lag_h[1])) return(0)
  row$optimal_lag_h[1]
}

# Build shifted tributary columns per-regime
df$mono_shifted  <- NA_real_
df$goose_shifted <- NA_real_

for (regime in regimes) {
  idx <- which(df$flow_regime == regime)
  if (length(idx) == 0) next

  mono_lag  <- get_optimal_lag("monocacy", regime)
  goose_lag <- get_optimal_lag("goose", regime)

  df$mono_shifted[idx]  <- lookup_lagged(ts_seconds[idx], mono_lag, mono_env)
  df$goose_shifted[idx] <- lookup_lagged(ts_seconds[idx], goose_lag, goose_env)
}

df$gf_shifted <- df$blended_por +
  df$mono_shifted  * 0.071 +
  df$goose_shifted * 0.030

# -- RMSE calculation per regime and overall ----------------------------------
rmse <- function(predicted, actual) {
  resid <- predicted - actual
  ok <- !is.na(resid)
  if (sum(ok) < 2) return(NA_real_)
  sqrt(mean(resid[ok]^2))
}

results <- data.frame(
  tributary        = character(),
  flow_regime      = character(),
  optimal_lag_h    = numeric(),
  peak_correlation = numeric(),
  rmse_current     = numeric(),
  rmse_shifted     = numeric(),
  rmse_change_pct  = numeric(),
  n_obs            = integer(),
  recommendation   = character(),
  stringsAsFactors = FALSE
)

# Per-regime RMSE (report one row per tributary per regime)
for (trib_name in c("monocacy", "goose")) {
  for (regime in regimes) {
    idx <- which(df$flow_regime == regime)
    if (length(idx) < 10) {
      results <- rbind(results, data.frame(
        tributary        = trib_name,
        flow_regime      = regime,
        optimal_lag_h    = NA_real_,
        peak_correlation = NA_real_,
        rmse_current     = NA_real_,
        rmse_shifted     = NA_real_,
        rmse_change_pct  = NA_real_,
        n_obs            = length(idx),
        recommendation   = "insufficient_data",
        stringsAsFactors = FALSE
      ))
      next
    }

    opt_row <- optimal_lags[optimal_lags$tributary == trib_name &
                            optimal_lags$flow_regime == regime, ]
    opt_lag  <- if (nrow(opt_row) > 0 && !is.na(opt_row$optimal_lag_h[1])) {
      opt_row$optimal_lag_h[1]
    } else {
      0
    }
    peak_cor <- if (nrow(opt_row) > 0 && !is.na(opt_row$peak_correlation[1])) {
      opt_row$peak_correlation[1]
    } else {
      NA_real_
    }
    n_obs_corr <- if (nrow(opt_row) > 0 && !is.na(opt_row$n_obs[1])) {
      opt_row$n_obs[1]
    } else {
      0L
    }

    # RMSE: computed on the FULL blended estimate (both tributaries),
    # so both rows (monocacy and goose for same regime) will show the same
    # overall RMSE. That is correct -- both tributaries contribute simultaneously.
    rmse_c <- rmse(df$gf_current[idx], df$lf_discharge[idx])
    rmse_s <- rmse(df$gf_shifted[idx], df$lf_discharge[idx])

    if (!is.na(rmse_c) && rmse_c > 0 && !is.na(rmse_s)) {
      change_pct <- (rmse_s - rmse_c) / rmse_c * 100
    } else {
      change_pct <- NA_real_
    }

    # Recommendation: implement if > 1% RMSE improvement (change_pct < -1)
    rec <- if (!is.na(change_pct) && change_pct < -1) {
      "implement"
    } else if (!is.na(change_pct)) {
      "no_change"
    } else {
      "insufficient_data"
    }

    results <- rbind(results, data.frame(
      tributary        = trib_name,
      flow_regime      = regime,
      optimal_lag_h    = opt_lag,
      peak_correlation = round(peak_cor, 6),
      rmse_current     = round(rmse_c, 2),
      rmse_shifted     = round(rmse_s, 2),
      rmse_change_pct  = round(change_pct, 4),
      n_obs            = as.integer(n_obs_corr),
      recommendation   = rec,
      stringsAsFactors = FALSE
    ))
  }
}

# -- Add overall rows ---------------------------------------------------------
for (trib_name in c("monocacy", "goose")) {
  # Overall RMSE across all regimes
  ok_c <- !is.na(df$gf_current) & !is.na(df$lf_discharge)
  ok_s <- !is.na(df$gf_shifted) & !is.na(df$lf_discharge)
  ok   <- ok_c & ok_s

  rmse_c <- rmse(df$gf_current[ok], df$lf_discharge[ok])
  rmse_s <- rmse(df$gf_shifted[ok], df$lf_discharge[ok])

  if (!is.na(rmse_c) && rmse_c > 0 && !is.na(rmse_s)) {
    change_pct <- (rmse_s - rmse_c) / rmse_c * 100
  } else {
    change_pct <- NA_real_
  }

  rec <- if (!is.na(change_pct) && change_pct < -1) {
    "implement"
  } else if (!is.na(change_pct)) {
    "no_change"
  } else {
    "insufficient_data"
  }

  results <- rbind(results, data.frame(
    tributary        = trib_name,
    flow_regime      = "overall",
    optimal_lag_h    = NA_real_,
    peak_correlation = NA_real_,
    rmse_current     = round(rmse_c, 2),
    rmse_shifted     = round(rmse_s, 2),
    rmse_change_pct  = round(change_pct, 4),
    n_obs            = sum(ok),
    recommendation   = rec,
    stringsAsFactors = FALSE
  ))
}

# -- Save output --------------------------------------------------------------
cat("\nWriting results to: " %s% output_f %s% "\n")
write.csv(results, output_f, row.names = FALSE)

# -- Print summary report -----------------------------------------------------
cat("\n" %s% strrep("=", 70) %s% "\n")
cat("TRIBUTARY TIMING VALIDATION REPORT (R)\n")
cat(strrep("=", 70) %s% "\n\n")

cat("Merged dataset: " %s% as.character(nrow(df)) %s% " hourly observations\n")
cat("Date range: " %s% as.character(min(df$timestamp, na.rm = TRUE)) %s%
    " to " %s% as.character(max(df$timestamp, na.rm = TRUE)) %s% "\n\n")

cat("Flow regime distribution:\n")
regime_table <- table(df$flow_regime)
for (r in names(regime_table)) {
  cat("  " %s% r %s% ": " %s% as.character(regime_table[r]) %s% " obs\n")
}

cat("\n" %s% strrep("-", 70) %s% "\n")
cat("OPTIMAL LAGS (from first-difference cross-correlation)\n")
cat(strrep("-", 70) %s% "\n")
for (i in seq_len(nrow(optimal_lags))) {
  row <- optimal_lags[i, ]
  cat(sprintf("  %-10s  %-8s  lag=%4.1fh  r=%.4f  n=%d\n",
              row$tributary, row$flow_regime,
              ifelse(is.na(row$optimal_lag_h), 0, row$optimal_lag_h),
              ifelse(is.na(row$peak_correlation), 0, row$peak_correlation),
              ifelse(is.na(row$n_obs), 0L, row$n_obs)))
}

cat("\n" %s% strrep("-", 70) %s% "\n")
cat("RMSE IMPACT\n")
cat(strrep("-", 70) %s% "\n")
cat(sprintf("  %-10s  %-8s  %10s  %10s  %8s  %s\n",
            "Tributary", "Regime", "RMSE_curr", "RMSE_shift", "Change%", "Action"))
cat(strrep("-", 70) %s% "\n")
for (i in seq_len(nrow(results))) {
  row <- results[i, ]
  cat(sprintf("  %-10s  %-8s  %10.2f  %10.2f  %7.3f%%  %s\n",
              row$tributary, row$flow_regime,
              ifelse(is.na(row$rmse_current), 0, row$rmse_current),
              ifelse(is.na(row$rmse_shifted), 0, row$rmse_shifted),
              ifelse(is.na(row$rmse_change_pct), 0, row$rmse_change_pct),
              row$recommendation))
}

cat("\n" %s% strrep("=", 70) %s% "\n")

# Final summary recommendation
overall_rows <- results[results$flow_regime == "overall", ]
any_implement <- any(overall_rows$recommendation == "implement", na.rm = TRUE)
if (any_implement) {
  cat("RECOMMENDATION: Implement tributary time-shifting (>1% RMSE improvement found)\n")
} else {
  cat("RECOMMENDATION: No change needed (improvement < 1% threshold)\n")
}

cat("Results saved to: " %s% output_f %s% "\n")
cat(strrep("=", 70) %s% "\n")
